import {React, useState} from 'react'
import NavItem from 'components/NavItem'
import Link from 'next/link'
import Script from 'next/script'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Navbar from 'components/Navbar'
import Card from 'components/Card'

const inter = Inter({ subsets: ['latin'] })


const Home = () => {
  const [navActive, setNavActive] = useState(null);
const [activeIdx, setActiveIdx] = useState(-1);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
       
      </Head>
      <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" />
      <main className={styles.main}>
      <Navbar/>
      <Card/>
      </main>
    </>
  );
}

export default Home;